config/routes.rb
Rails.application.routes.draw do
  # ...
  namespace :api do
    namespace :v1 do
      # Authentication routes
      get '/users/search', to: 'users#search'
      post '/login', to: 'auth#login'
      get '/current_user', to: 'auth#current_user'
      post '/signup', to: 'registrations#create'
      delete '/logout', to: 'auth#logout'
      # Custom routes for contents
      resources :contents, only: [:new, :create, :show, :update, :destroy] do
        post :like, on: :member
        post :view, on: :member
        post :create_comment, on: :member
      end
      # Posts routes
      resources :posts, only: [:index, :create, :update, :destroy, :show] do
        member do
          get :likes
          put :like
          get :all_comments
        end
        resources :comments, only: [:index, :create], param: :id
      end
      get '/posts/timeline/:user_id', to: 'posts#timeline'
      get '/posts/profile/:username', to: 'posts#profile'
      # Posts routes
      post '/upload', to: 'posts#upload'
      mount ActionCable.server => '/cable'
      # Tags routes
      resources :tags, only: [:index, :new, :create, :show]
      # Notifications routes
      resources :notifications, only: [:index, :show, :update] do
        member do
          patch :mark_as_read
        end
        collection do
          patch :mark_multiple_as_read
          post :create_notification  # Add this line to include the new action
        end
      end
      #users
      resources :users, only: [:index, :show, :update, :destroy] do
        member do
          put :follow
          put :unfollow
          put :update_profile
          get :friends
          get :profile
          match :update_profile_picture, via: [:put, :patch]
          match :update_cover_picture, via: [:put, :patch]
          match :update_bio, via: [:put, :patch]
        end
      end
      # Comments routes
      resources :comments, only: [:index, :show, :create, :update, :destroy] do
        member do
          put :like_comment
          delete :unlike_comment
        end
      end
      # Route for the PrivateController
      get '/private/test', to: 'private#test'
      get '/private/auth_params', to: 'private#auth_params'
      # Fallback route for handling client-side routing (e.g., React, Vue, etc.)
      get '*path', to: 'fallback#index', constraints: ->(req) { !req.xhr? && req.format.html? }
    end
  end
end

app/views/layouts/content/_form.html.erb
<div class="field">
  <%= form.label :category_ids, "Categories" %>
  <%= form.collection_select :category_ids, Category.all, :id, :category_name, {}, multiple: true %>
</div>

<div class="field">
  <%= form.label :tag_ids, "Tags" %>
  <%= form.collection_select :tag_ids, Tag.all, :id, :name, {}, multiple: true %>
</div>

app/views/layouts/content/index.hml.erb
<h1>Contents</h1>

<ul>
  <% @contents.each do |content| %>
    <li>
      <%= link_to content.title, content %>
    </li>
  <% end %>
</ul>

<%= link_to 'New Content', new_content_path %>

app/views/layouts/content/show.html.erb
<h1><%= @content.title %></h1>
<p><%= @content.body %></p>

<!-- Like button -->
<%= button_to 'Like', like_content_path(@content), method: :post %>
<span>Likes: <%= @content.likes_count %></span>

<!-- View button -->
<%= button_to 'View', view_content_path(@content), method: :post %>
<span>Views: <%= @content.views_count %></span>

<!-- Comment form -->
<%= form_with(model: @content, url: comment_content_path(@content), method: :post) do |form| %>
  <%= form.text_area :body %>
  <%= form.submit 'Add Comment' %>
<% end %>

<h2>Comments</h2>
<% @content.comments.each do |comment| %>
  <p><%= comment.body %></p>
<% end %>